name: Sign and Upload NuGet

on:
  release:
   types: [ published ]
  workflow_dispatch:
    inputs:
      version_tag:
        description: Tag of the release to notarize
        required: true
        type: string
      beta:
        description: If true - loads given nuget as beta version
        required: false
        type: boolean
        default: false  

jobs:
  setup:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - uses: actions-ecosystem/action-get-latest-tag@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: get-latest-tag
      
      - name: Set latest version tag to ENV
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          version_tag=${{ steps.get-latest-tag.outputs.tag }}
          echo ${version_tag}
          version_tag=${version_tag%%-*}
          echo "version_tag=${version_tag}" >> "$GITHUB_ENV"

      - name: Set user provided version tag to ENV
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          version_tag=${{ inputs.version_tag }}
          echo ${version_tag}
          version_tag=${version_tag%%-*}
          echo "version_tag=${version_tag}" >> "$GITHUB_ENV"
      
      - name: Output tag from ENV
        id: get-tag
        run: |
          version_tag=${{ env.version_tag }}
          echo ${version_tag}
          version_tag=${version_tag%%-*}
          echo "version_tag=${version_tag}" >> "$GITHUB_OUTPUT"

  sign-upload:
    timeout-minutes: 10
    needs: setup
    runs-on: [windows-x64-codesign]
    steps:
      - name: Remove old local NuGet packages
        run: Remove-Item "MeshLib_*.nupkg"
        
      - name: Download NuGet package
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download ${{needs.setup.outputs.version_tag}} `
                              --repo $env:GITHUB_REPOSITORY `
                              --pattern "MeshLib_${{needs.setup.outputs.version_tag}}.nupkg"    
     
      - name: Make Beta
        if: ${{ inputs.beta }}
        run: py -3 scripts\nuget_patch\nuget_make_beta.py "MeshLib_${{needs.setup.outputs.version_tag}}.nupkg"

      - name: Sign NuGet package with certificate
        run: |
          jsign --storetype ETOKEN --storepass "${{ secrets.WINDOWS_SIGNTOOL_KC_PARAM_TOKEN_PASSWORD }}" -tsaurl http://timestamp.digicert.com MeshLib_${{needs.setup.outputs.version_tag}}.nupkg
          nuget verify -All -Verbosity detailed MeshLib_${{needs.setup.outputs.version_tag}}.nupkg
      
      - name: Upload signed NuGet package
        run: |
          nuget push MeshLib_${{needs.setup.outputs.version_tag}}.nupkg ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
