name: Update MeshLib app containers

on:
  #release:
    #types: [ published ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-app-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ Ubuntu-20, Ubuntu-22 ]
        include:
          - os: Ubuntu-20
            image-tag: ubuntu20
            file-path-end: _ubuntu20-dev.deb
          - os: Ubuntu-22
            image-tag: ubuntu22
            file-path-end: _ubuntu22-dev.deb
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latests release
        id: get_release
        uses: kaliber5/action-get-release@953a6dd072cb35590892a224b72ba0ec6bef03a1 # v1
        with:
          token: ${{ secrets.BUILD_MACHINE_TOKEN }}
          latest: true

      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          username: meshlib
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set variables
        id: set-vars
        run: |
          echo "file_name=meshlib_${{steps.get_release.outputs.tag_name }}${{matrix.file-path-end}}" >> $GITHUB_OUTPUT
          echo "file_url=https://github.com/MeshInspector/MeshLib/releases/download/${{steps.get_release.outputs.tag_name}}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          file: ./docker/app/${{matrix.image-tag}}Dockerfile
          push: true
          tags: meshlib/meshlib-app:${{ matrix.image-tag }}-${{steps.get_release.outputs.tag_name }}, meshlib/meshlib-app:${{ matrix.image-tag }}
          build-args: |
            FILE_NAME=${{steps.set-vars.outputs.file_name}}
            FILE_URL=${{steps.set-vars.outputs.file_url}}/${{steps.set-vars.outputs.file_name}}
